#!/bin/bash
# Available environment variables:
# $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
# $NAUTILUS_SCRIPT_SELECTED_URIS
# $NAUTILUS_SCRIPT_CURRENT_URI
# $NAUTILUS_SCRIPT_WINDOW_GEOMETRY

# Remove trailing linefeed.
export file="${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS:0:-1}"
[[ ! -f $file || ! $file =~ flatpakref$ ]] && echo 'File must have a .flatpakref extension' exit 1
flatpak install "$file"
gnome-terminal -- bash -i -c "flatpak install "$file"; echo 'Press Enter to exit'; read"
# gnome-terminal -- bash -c "$(cat $HOME/.geo-cli/data/geo/repo-dir)/src/geo-cli.sh mydecoder $file; echo 'Press Enter to exit'; read"

